# FICHIER: ./.github/workflows/test-supabase-config.yml

name: Test Task Generation

on:
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Date cible (YYYY-MM-DD) - optionnel, défaut: demain'
        required: false
        type: string

jobs:
  test-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install @supabase/supabase-js

      - name: Generate daily tasks (TEST)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          TARGET_DATE: ${{ github.event.inputs.target_date || '' }}
        run: node scripts/generate-daily-tasks.js