# FICHIER: ./.github/workflows/test-supabase-config.yml

name: Test Supabase Configuration

on:
  workflow_dispatch: # Seulement exécution manuelle

jobs:
  test-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install @supabase/supabase-js

      - name: Test Supabase connection
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: node scripts/test-supabase-config.js